[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
community_registry = "5jgs47wXR92SMDzyG5LznPy95S6dohLuCKdQyCpEjTbp"
governance = "5abk3TPAhghaTvyxLYGRdY7YktHGKtJvxtyUYAtMwqqi"
membership = "ANra85R8oRawbSQu4z9yKjC8z7dcCyqeDJ5LzK4sonsa"
payment_attestation = "CCDYCTxAHREYgowDHViefiGUpvvN16JyiBiQhTdLtqCo"
treasury_vault = "BjECSjJWMAn13eVJftch45f1LNYXa95UMTRp7S77M6wS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/community_registry", "programs/governance", "programs/membership", "programs/payment_attestation", "programs/treasury_vault"]

[scripts]
test = "node tests/anchor-smoke.mjs"
