- generic [ref=e1]:
  - generic [ref=e5]:
    - generic [ref=e6]:
      - generic [ref=e7]:
        - generic [ref=e8]:
          - link "Claude" [ref=e9] [cursor=pointer]:
            - /url: https://claude.ai
            - img "Claude" [ref=e10]
          - generic [ref=e12]: Content is user-generated and unverified.
        - generic [ref=e13]:
          - img [ref=e14]
          - generic [ref=e16]: "1"
      - generic [ref=e17]:
        - button "Copy link" [ref=e20] [cursor=pointer]:
          - img [ref=e21]
        - button "Report" [ref=e25] [cursor=pointer]:
          - img [ref=e26]
        - button "Customize" [ref=e28] [cursor=pointer]:
          - img [ref=e29]
          - text: Customize
    - iframe [active] [ref=e36]:
      - generic [ref=f1e1]:
        - alert [ref=f1e2]
        - generic [ref=f1e4]:
          - generic [ref=f1e5]:
            - generic [ref=f1e6]:
              - generic [ref=f1e7]: BARAZA
              - generic [ref=f1e8]: Product Requirements
              - generic [ref=f1e9]: v1.0 · Pre-Product
            - generic [ref=f1e10]:
              - button "01 Overview" [ref=f1e11] [cursor=pointer]
              - button "02 Problem" [ref=f1e12] [cursor=pointer]
              - button "03 Vision" [ref=f1e13] [cursor=pointer]
              - button "04 Personas" [ref=f1e14] [cursor=pointer]
              - button "05 Features" [ref=f1e15] [cursor=pointer]
              - button "06 Baraza AI" [ref=f1e16] [cursor=pointer]
              - button "07 Escrow & Payments" [ref=f1e17] [cursor=pointer]
              - button "08 Technical" [ref=f1e18] [cursor=pointer]
              - button "09 User Flows" [ref=f1e19] [cursor=pointer]
              - button "10 Revenue" [ref=f1e20] [cursor=pointer]
              - button "11 Metrics & KPIs" [ref=f1e21] [cursor=pointer]
              - button "12 Roadmap" [ref=f1e22] [cursor=pointer]
              - button "13 Risk Register" [ref=f1e23] [cursor=pointer]
              - button "14 Competitive" [active] [ref=f1e24] [cursor=pointer]
            - generic [ref=f1e26]:
              - text: Build Africa DAO
              - text: Confidential · 2025
          - generic [ref=f1e28]:
            - generic [ref=f1e29]:
              - generic [ref=f1e30]: SECTION 14
              - heading "Competitive Landscape" [level=2] [ref=f1e1137]
              - paragraph [ref=f1e32]: Who exists, why they fall short, and where Baraza wins.
            - generic [ref=f1e1138]:
              - generic [ref=f1e1140]:
                - generic [ref=f1e1141]:
                  - generic [ref=f1e1142]: Aragon / Tally / Snapshot
                  - generic [ref=f1e1143]: DAO Tools
                  - paragraph [ref=f1e1144]: Governance infrastructure for crypto-native DAOs
                - generic [ref=f1e1145]:
                  - generic [ref=f1e1146]: Where They Fall Short
                  - paragraph [ref=f1e1147]: Requires existing crypto wallets. No fiat on-ramp. No AI layer. No marketplace. No growth markets. English-only. No Africa presence.
                - generic [ref=f1e1148]:
                  - generic [ref=f1e1149]: Where Baraza Wins
                  - paragraph [ref=f1e1150]: Baraza adds fiat rails, AI, marketplace, growth markets, and business onboarding. Snapshot users can import their DAOs to Baraza and immediately unlock these layers.
              - generic [ref=f1e1152]:
                - generic [ref=f1e1153]:
                  - generic [ref=f1e1154]: Yellow Card / Chipper Cash
                  - generic [ref=f1e1155]: African Fintech
                  - paragraph [ref=f1e1156]: Fiat-to-crypto exchange for Africa
                - generic [ref=f1e1157]:
                  - generic [ref=f1e1158]: Where They Fall Short
                  - paragraph [ref=f1e1159]: Exchange infrastructure only. No community layer. No governance. No NFTs. No AI. No project marketplace. Users go there to buy crypto, not to build communities.
                - generic [ref=f1e1160]:
                  - generic [ref=f1e1161]: Where Baraza Wins
                  - paragraph [ref=f1e1162]: "Baraza is not a competitor — it is the destination layer on top of these rails. Partnership opportunity: Baraza as a use case for Yellow Card users."
              - generic [ref=f1e1164]:
                - generic [ref=f1e1165]:
                  - generic [ref=f1e1166]: Mighty Networks / Circle.so
                  - generic [ref=f1e1167]: Community Platforms
                  - paragraph [ref=f1e1168]: Web2 community building for businesses and creators
                - generic [ref=f1e1169]:
                  - generic [ref=f1e1170]: Where They Fall Short
                  - paragraph [ref=f1e1171]: No blockchain. No ownership. No treasury. No governance. No AI agents. Members contribute but hold nothing. Platform extracts value.
                - generic [ref=f1e1172]:
                  - generic [ref=f1e1173]: Where Baraza Wins
                  - paragraph [ref=f1e1174]: Baraza gives every community member actual equity and governance rights. The same use case, with ownership built in.
              - generic [ref=f1e1176]:
                - generic [ref=f1e1177]:
                  - generic [ref=f1e1178]: Gitcoin / Coordinape
                  - generic [ref=f1e1179]: Web3 Contribution
                  - paragraph [ref=f1e1180]: Grant distribution and contributor coordination for DAOs
                - generic [ref=f1e1181]:
                  - generic [ref=f1e1182]: Where They Fall Short
                  - paragraph [ref=f1e1183]: Crypto-only. No fiat. No Africa focus. No AI scoring. No business communities. No growth markets. Very developer-centric.
                - generic [ref=f1e1184]:
                  - generic [ref=f1e1185]: Where Baraza Wins
                  - paragraph [ref=f1e1186]: Baraza's marketplace serves all skill types — design, writing, strategy, operations — not just developers. And any contributor can get paid to M-Pesa.
              - generic [ref=f1e1188]:
                - generic [ref=f1e1189]:
                  - generic [ref=f1e1190]: Rally / Friends with Benefits
                  - generic [ref=f1e1191]: Social Tokens
                  - paragraph [ref=f1e1192]: Creator and community tokenisation
                - generic [ref=f1e1193]:
                  - generic [ref=f1e1194]: Where They Fall Short
                  - paragraph [ref=f1e1195]: US/global crypto-native audience only. No fiat on-ramp for Africa. No governance depth. No AI. No business tier. No project marketplace.
                - generic [ref=f1e1196]:
                  - generic [ref=f1e1197]: Where Baraza Wins
                  - paragraph [ref=f1e1198]: Baraza targets communities doing real work and real governance — not just social status tokens. The growth market is backed by objective fundamentals, not vibes.
            - generic [ref=f1e1199]:
              - generic [ref=f1e1200]: The Unfair Advantage
              - paragraph [ref=f1e1201]: No competitor combines fiat mobile-money rails, AI-powered community governance, a project marketplace, business-to-DAO upgrade paths, and a growth investment market — on a single platform, built for Africa, designed for the world. The escrow system is not a feature. It is the moat.
  - alert [ref=e38]
  - iframe [ref=e39]:
    