- generic [ref=e1]:
  - generic [ref=e5]:
    - generic [ref=e6]:
      - generic [ref=e7]:
        - generic [ref=e8]:
          - link "Claude" [ref=e9] [cursor=pointer]:
            - /url: https://claude.ai
            - img "Claude" [ref=e10]
          - generic [ref=e12]: Content is user-generated and unverified.
        - generic [ref=e13]:
          - img [ref=e14]
          - generic [ref=e16]: "1"
      - generic [ref=e17]:
        - button "Copy link" [ref=e20] [cursor=pointer]:
          - img [ref=e21]
        - button "Report" [ref=e25] [cursor=pointer]:
          - img [ref=e26]
        - button "Customize" [ref=e28] [cursor=pointer]:
          - img [ref=e29]
          - text: Customize
    - iframe [active] [ref=e36]:
      - generic [ref=f1e1]:
        - alert [ref=f1e2]
        - generic [ref=f1e4]:
          - generic [ref=f1e5]:
            - generic [ref=f1e6]:
              - generic [ref=f1e7]: BARAZA
              - generic [ref=f1e8]: Product Requirements
              - generic [ref=f1e9]: v1.0 · Pre-Product
            - generic [ref=f1e10]:
              - button "01 Overview" [ref=f1e11] [cursor=pointer]
              - button "02 Problem" [ref=f1e12] [cursor=pointer]
              - button "03 Vision" [ref=f1e13] [cursor=pointer]
              - button "04 Personas" [active] [ref=f1e14] [cursor=pointer]
              - button "05 Features" [ref=f1e15] [cursor=pointer]
              - button "06 Baraza AI" [ref=f1e16] [cursor=pointer]
              - button "07 Escrow & Payments" [ref=f1e17] [cursor=pointer]
              - button "08 Technical" [ref=f1e18] [cursor=pointer]
              - button "09 User Flows" [ref=f1e19] [cursor=pointer]
              - button "10 Revenue" [ref=f1e20] [cursor=pointer]
              - button "11 Metrics & KPIs" [ref=f1e21] [cursor=pointer]
              - button "12 Roadmap" [ref=f1e22] [cursor=pointer]
              - button "13 Risk Register" [ref=f1e23] [cursor=pointer]
              - button "14 Competitive" [ref=f1e24] [cursor=pointer]
            - generic [ref=f1e26]:
              - text: Build Africa DAO
              - text: Confidential · 2025
          - generic [ref=f1e28]:
            - generic [ref=f1e29]:
              - generic [ref=f1e30]: SECTION 04
              - heading "User Personas" [level=2] [ref=f1e1202]
              - paragraph [ref=f1e32]: Four primary personas Baraza must serve from day one.
            - generic [ref=f1e1204]:
              - generic [ref=f1e1205]:
                - generic [ref=f1e1206]: P1
                - generic [ref=f1e1207]: Amara
                - generic [ref=f1e1208]: DAO Founder
                - paragraph [ref=f1e1209]: 28-year-old tech entrepreneur in Nairobi. Runs a crypto-native community of 200 developers. Currently uses Snapshot for governance, Discord for discussion, and Gnosis Safe for treasury. Constantly context-switching across tools.
              - generic [ref=f1e1210]:
                - generic [ref=f1e1211]:
                  - generic [ref=f1e1212]: Goals
                  - generic [ref=f1e1213]: 1. Single platform for governance, treasury, and community
                  - generic [ref=f1e1214]: 2. AI that follows up on stalled proposals
                  - generic [ref=f1e1215]: 3. Reward active contributors with real equity
                  - generic [ref=f1e1216]: 4. Attract investors to his DAO's growth token
                - generic [ref=f1e1217]:
                  - generic [ref=f1e1218]: Pain Points
                  - generic [ref=f1e1219]: 1. Snapshot requires existing crypto wallets — hard to onboard new members
                  - generic [ref=f1e1220]: 2. No accountability after votes pass — proposals die
                  - generic [ref=f1e1221]: 3. No way for believers to invest in the DAO's growth
                - generic [ref=f1e1222]:
                  - generic [ref=f1e1223]: Journey
                  - generic [ref=f1e1224]: 1. Discovers Baraza via Build Africa DAO
                  - generic [ref=f1e1225]: 2. Launches DAO in < 10 minutes
                  - generic [ref=f1e1226]: 3. Migrates existing treasury
                  - generic [ref=f1e1227]: 4. Deploys Baraza AI
                  - generic [ref=f1e1228]: 5. Launches membership NFTs
                  - generic [ref=f1e1229]: 6. Activates growth token on market
            - generic [ref=f1e1231]:
              - generic [ref=f1e1232]:
                - generic [ref=f1e1233]: P2
                - generic [ref=f1e1234]: Wanjiru
                - generic [ref=f1e1235]: Business Owner
                - paragraph [ref=f1e1236]: 42-year-old founder of a mid-sized fashion brand in Nairobi. 15,000 Instagram followers. Has never used crypto. Wants to build a loyal community that feels ownership over the brand and gives structured product feedback.
              - generic [ref=f1e1237]:
                - generic [ref=f1e1238]:
                  - generic [ref=f1e1239]: Goals
                  - generic [ref=f1e1240]: 1. Customer community that gives structured feedback
                  - generic [ref=f1e1241]: 2. Reward loyal customers with real benefits
                  - generic [ref=f1e1242]: 3. Structured suggestion and voting system
                  - generic [ref=f1e1243]: 4. Eventually explore tokenising brand equity
                - generic [ref=f1e1244]:
                  - generic [ref=f1e1245]: Pain Points
                  - generic [ref=f1e1246]: 1. Instagram comments are unstructured noise
                  - generic [ref=f1e1247]: 2. No way to give top customers real ownership
                  - generic [ref=f1e1248]: 3. Doesn't understand crypto — needs zero-friction entry
                - generic [ref=f1e1249]:
                  - generic [ref=f1e1250]: Journey
                  - generic [ref=f1e1251]: 1. Signs up with email + phone
                  - generic [ref=f1e1252]: 2. Creates a Business Community (no wallet needed)
                  - generic [ref=f1e1253]: 3. Invites customers via WhatsApp link
                  - generic [ref=f1e1254]: "4. Runs first proposal: new product line vote"
                  - generic [ref=f1e1255]: 5. Sees engagement data on dashboard
                  - generic [ref=f1e1256]: 6. Baraza AI suggests upgrading to DAO tier
            - generic [ref=f1e1258]:
              - generic [ref=f1e1259]:
                - generic [ref=f1e1260]: P3
                - generic [ref=f1e1261]: Kofi
                - generic [ref=f1e1262]: Community Member / Contributor
                - paragraph [ref=f1e1263]: 23-year-old freelance designer in Accra. Active in 3 online communities. Wants to monetise his skills through DAOs, build a verifiable on-chain reputation, and hold equity in the communities he helps grow.
              - generic [ref=f1e1264]:
                - generic [ref=f1e1265]:
                  - generic [ref=f1e1266]: Goals
                  - generic [ref=f1e1267]: 1. Find well-paid design and creative bounties
                  - generic [ref=f1e1268]: 2. Build portable on-chain reputation
                  - generic [ref=f1e1269]: 3. Hold equity (NFT cards) in DAOs he believes in
                  - generic [ref=f1e1270]: 4. Simple onboarding — no crypto knowledge required
                - generic [ref=f1e1271]:
                  - generic [ref=f1e1272]: Pain Points
                  - generic [ref=f1e1273]: 1. Can't find reliable crypto jobs without a portfolio
                  - generic [ref=f1e1274]: 2. Getting paid across borders is expensive and slow
                  - generic [ref=f1e1275]: 3. No way to prove his contribution history to new communities
                - generic [ref=f1e1276]:
                  - generic [ref=f1e1277]: Journey
                  - generic [ref=f1e1278]: 1. Joins Baraza via M-Pesa wallet
                  - generic [ref=f1e1279]: 2. Discovers job listings in communities
                  - generic [ref=f1e1280]: 3. Submits work to a design bounty
                  - generic [ref=f1e1281]: 4. Baraza AI scores submission fairly
                  - generic [ref=f1e1282]: 5. Gets paid to MoMo wallet
                  - generic [ref=f1e1283]: 6. Reputation score rises across platform
            - generic [ref=f1e1285]:
              - generic [ref=f1e1286]:
                - generic [ref=f1e1287]: P4
                - generic [ref=f1e1288]: Diaspora David
                - generic [ref=f1e1289]: Investor / Backer
                - paragraph [ref=f1e1290]: 35-year-old Kenyan software engineer in London. Wants to invest in African community growth. Holds some crypto. Wants to back specific communities he believes in — not just buy random tokens — and see real fundamentals behind the investment.
              - generic [ref=f1e1291]:
                - generic [ref=f1e1292]:
                  - generic [ref=f1e1293]: Goals
                  - generic [ref=f1e1294]: 1. Invest in high-growth African DAOs and businesses
                  - generic [ref=f1e1295]: 2. See real metrics behind the communities he backs
                  - generic [ref=f1e1296]: 3. Receive dividends or token appreciation as DAOs grow
                  - generic [ref=f1e1297]: 4. Feel connected to communities back home
                - generic [ref=f1e1298]:
                  - generic [ref=f1e1299]: Pain Points
                  - generic [ref=f1e1300]: 1. African crypto projects are opaque and speculative
                  - generic [ref=f1e1301]: 2. No platform shows real community health metrics
                  - generic [ref=f1e1302]: 3. Hard to move money home cheaply and quickly
                - generic [ref=f1e1303]:
                  - generic [ref=f1e1304]: Journey
                  - generic [ref=f1e1305]: 1. Discovers Baraza Growth Markets
                  - generic [ref=f1e1306]: 2. Browses DAO leaderboard with growth scores
                  - generic [ref=f1e1307]: 3. Buys tokens via bank transfer or SWIFT
                  - generic [ref=f1e1308]: 4. Monitors DAO activity via dashboard
                  - generic [ref=f1e1309]: 5. Refers other diaspora investors
                  - generic [ref=f1e1310]: 6. Participates in DAO governance if he holds membership NFT
  - alert [ref=e38]
  - iframe [ref=e39]:
    